// Sample data shipped with the static demo so first-time visitors land on a
// pre-populated CRM instead of an empty shell.

import type {
  Activity,
  ApiToken,
  AuditEntry,
  Automation,
  Campaign,
  Company,
  Contact,
  Deal,
  EmailEvent,
  EmailRecord,
  Enrollment,
  FormDef,
  Lead,
  Meeting,
  Member,
  Pipeline,
  SavedView,
  ScheduledEmail,
  Sequence,
  SequenceStep,
  Snippet,
  SuppressionEntry,
  TagDef,
  Task,
  Template,
  Webhook,
} from "../types";

const NOW = "2026-04-30T10:00:00.000Z";
const D = (offsetDays: number) =>
  new Date(Date.parse(NOW) + offsetDays * 24 * 3600 * 1000).toISOString();

export const SEED_CONTACTS: Contact[] = [
  {
    id: "c_demo_001",
    name: "Maya Chen",
    email: "maya.chen@northwind.example",
    company: "Northwind Logistics",
    role: "VP Sales",
    phone: "+1 415 555 0142",
    linkedin: "https://linkedin.com/in/mayachen",
    tags: "ICP, mid-market",
    notes: "Met at SaaStr; expanding into EU next quarter.",
    createdAt: D(-21),
    updatedAt: D(-2),
  },
  {
    id: "c_demo_002",
    name: "Diego Alvarez",
    email: "diego@brightleaf.example",
    company: "Brightleaf Analytics",
    role: "Head of Growth",
    phone: "",
    linkedin: "https://linkedin.com/in/diegoalvarez",
    tags: "ICP, replied",
    notes: "Cares about pipeline analytics. Wants to see funnel reports.",
    createdAt: D(-14),
    updatedAt: D(-1),
  },
  {
    id: "c_demo_003",
    name: "Priya Nair",
    email: "priya@tidewater.example",
    company: "Tidewater AI",
    role: "Founder",
    phone: "",
    linkedin: "",
    tags: "ICP, founder",
    notes: "Series A, 25 people. Looking for outbound tooling.",
    createdAt: D(-9),
    updatedAt: D(-1),
  },
  {
    id: "c_demo_004",
    name: "Tom Becker",
    email: "tbecker@apexpartners.example",
    company: "Apex Partners",
    role: "Partner",
    phone: "",
    linkedin: "",
    tags: "investor",
    notes: "Intro from board; warm.",
    createdAt: D(-7),
    updatedAt: D(-3),
  },
  {
    id: "c_demo_005",
    name: "Sara Okafor",
    email: "sara.okafor@helixmed.example",
    company: "Helix Medical",
    role: "Director of Sales Ops",
    phone: "",
    linkedin: "",
    tags: "ICP, healthcare",
    notes: "Procurement gate is RevOps. Loop in IT.",
    createdAt: D(-5),
    updatedAt: D(-1),
  },
  {
    id: "c_demo_006",
    name: "Liam O'Connor",
    email: "liam@drift-bay.example",
    company: "Drift Bay",
    role: "Sales Manager",
    phone: "",
    linkedin: "",
    tags: "ICP",
    notes: "From CSV import.",
    createdAt: D(-3),
    updatedAt: D(-3),
  },
  {
    id: "c_demo_007",
    name: "Aiko Tanaka",
    email: "aiko@northwind.example",
    company: "Northwind Logistics",
    role: "Sales Engineer",
    phone: "",
    linkedin: "",
    tags: "champion",
    notes: "Maya's deputy. Pre-sold; needs ammunition.",
    createdAt: D(-2),
    updatedAt: D(-2),
  },
  {
    id: "c_demo_008",
    name: "Noah Rivera",
    email: "noah@cobalt-lab.example",
    company: "Cobalt Lab",
    role: "COO",
    phone: "",
    linkedin: "",
    tags: "ICP",
    notes: "Form submission from /f/contact-us.",
    createdAt: D(-1),
    updatedAt: D(-1),
  },
  {
    id: "c_demo_009",
    name: "Hannah Weiss",
    email: "hannah.weiss@summitfin.example",
    company: "Summit Financial",
    role: "VP of Revenue",
    phone: "+1 212 555 0118",
    linkedin: "https://linkedin.com/in/hannahweiss",
    tags: "ICP, fintech",
    notes: "Series C; 60-person sales org. Looking at sequencing tools.",
    createdAt: D(-30),
    updatedAt: D(-4),
  },
  {
    id: "c_demo_010",
    name: "Jamal Williams",
    email: "jamal@harborline.example",
    company: "Harborline",
    role: "Director of Sales",
    phone: "",
    linkedin: "",
    tags: "ICP",
    notes: "Cold inbound from website. Demoed last quarter, went silent.",
    createdAt: D(-25),
    updatedAt: D(-10),
  },
  {
    id: "c_demo_011",
    name: "Yuki Sato",
    email: "yuki@orbital-os.example",
    company: "Orbital OS",
    role: "Founder & CEO",
    phone: "",
    linkedin: "https://linkedin.com/in/yukisato",
    tags: "ICP, founder, replied",
    notes: "Replied positively to founder sequence. Wants to see ROI math.",
    createdAt: D(-20),
    updatedAt: D(-2),
  },
  {
    id: "c_demo_012",
    name: "Carlos Mendoza",
    email: "cmendoza@northwind.example",
    company: "Northwind Logistics",
    role: "Director of RevOps",
    phone: "",
    linkedin: "",
    tags: "champion",
    notes: "Maya's RevOps lead. Owns the tooling decision.",
    createdAt: D(-18),
    updatedAt: D(-3),
  },
  {
    id: "c_demo_013",
    name: "Esther Park",
    email: "esther@bluepine.example",
    company: "Bluepine Health",
    role: "Head of GTM",
    phone: "",
    linkedin: "",
    tags: "ICP, healthcare",
    notes: "Met at HIMSS. Pre-qualifying for Q3.",
    createdAt: D(-16),
    updatedAt: D(-5),
  },
  {
    id: "c_demo_014",
    name: "Wei Zhang",
    email: "wei@quanta-mk.example",
    company: "Quanta Markets",
    role: "Head of BizDev",
    phone: "",
    linkedin: "",
    tags: "ICP, fintech",
    notes: "Prefers async; replies to short emails only.",
    createdAt: D(-15),
    updatedAt: D(-2),
  },
  {
    id: "c_demo_015",
    name: "Lena Kowalski",
    email: "lena@brightleaf.example",
    company: "Brightleaf Analytics",
    role: "Sales Operations Lead",
    phone: "",
    linkedin: "",
    tags: "champion",
    notes: "Diego's deputy. Will run the trial.",
    createdAt: D(-13),
    updatedAt: D(-2),
  },
  {
    id: "c_demo_016",
    name: "Marcus Hale",
    email: "marcus@gridworks.example",
    company: "Gridworks",
    role: "VP Sales",
    phone: "",
    linkedin: "",
    tags: "ICP",
    notes: "Replied to step 1; ghosted on step 2.",
    createdAt: D(-12),
    updatedAt: D(-6),
  },
  {
    id: "c_demo_017",
    name: "Sofia Iglesias",
    email: "sofia@palette-co.example",
    company: "Palette",
    role: "Marketing Director",
    phone: "",
    linkedin: "",
    tags: "marketing",
    notes: "Owns demand gen budget but defers to sales for tooling.",
    createdAt: D(-11),
    updatedAt: D(-4),
  },
  {
    id: "c_demo_018",
    name: "Olu Adebayo",
    email: "olu@stride-tx.example",
    company: "Stride TX",
    role: "Head of Sales",
    phone: "",
    linkedin: "",
    tags: "ICP",
    notes: "Replaced previous tool last quarter. Open to a chat in Q3.",
    createdAt: D(-10),
    updatedAt: D(-1),
  },
  {
    id: "c_demo_019",
    name: "Ravi Subramanian",
    email: "ravi@meadowlark-ai.example",
    company: "Meadowlark AI",
    role: "CEO",
    phone: "",
    linkedin: "",
    tags: "ICP, founder",
    notes: "Exited last company, raising $8M for this one.",
    createdAt: D(-9),
    updatedAt: D(-1),
  },
  {
    id: "c_demo_020",
    name: "Kira Larsen",
    email: "kira@ridgeline-bio.example",
    company: "Ridgeline Bio",
    role: "Director of Commercial",
    phone: "",
    linkedin: "",
    tags: "ICP, healthcare",
    notes: "Long sales cycle. Needs case study.",
    createdAt: D(-8),
    updatedAt: D(-3),
  },
  {
    id: "c_demo_021",
    name: "Drew Bartlett",
    email: "drew@pivotgear.example",
    company: "Pivotgear",
    role: "Founder",
    phone: "",
    linkedin: "",
    tags: "ICP, founder",
    notes: "Pre-seed. Tight budget but high intent.",
    createdAt: D(-6),
    updatedAt: D(-2),
  },
  {
    id: "c_demo_022",
    name: "Amara Singh",
    email: "amara@vellum-pay.example",
    company: "Vellum Pay",
    role: "VP RevOps",
    phone: "",
    linkedin: "",
    tags: "ICP, fintech",
    notes: "Inbound demo request. Hot.",
    createdAt: D(-4),
    updatedAt: D(-1),
  },
  {
    id: "c_demo_023",
    name: "Henrik Olsson",
    email: "henrik@arcfield.example",
    company: "Arcfield",
    role: "Sales Manager",
    phone: "",
    linkedin: "",
    tags: "",
    notes: "From CSV import; not yet enriched.",
    createdAt: D(-3),
    updatedAt: D(-3),
  },
  {
    id: "c_demo_024",
    name: "Elena Rossi",
    email: "elena@helixmed.example",
    company: "Helix Medical",
    role: "IT Director",
    phone: "",
    linkedin: "",
    tags: "champion",
    notes: "Sara's IT counterpart. Will sponsor security review.",
    createdAt: D(-3),
    updatedAt: D(-2),
  },
  {
    id: "c_demo_025",
    name: "Patrick O'Neill",
    email: "patrick@coppergate.example",
    company: "Coppergate",
    role: "VP Sales",
    phone: "",
    linkedin: "",
    tags: "ICP",
    notes: "Replied to A/B variant B; preferred shorter subject.",
    createdAt: D(-2),
    updatedAt: D(-1),
  },
  {
    id: "c_demo_026",
    name: "Mei Lin",
    email: "mei@firstwave.example",
    company: "Firstwave",
    role: "Head of Sales",
    phone: "",
    linkedin: "",
    tags: "ICP",
    notes: "Form submission from /f/demo-request.",
    createdAt: D(-1),
    updatedAt: D(-1),
  },
  {
    id: "c_demo_027",
    name: "Thomas Beaumont",
    email: "thomas@sparrowfin.example",
    company: "Sparrow Fin",
    role: "COO",
    phone: "",
    linkedin: "",
    tags: "ICP, fintech",
    notes: "Procurement ahead of Q3 budgeting.",
    createdAt: D(-1),
    updatedAt: D(-1),
  },
  {
    id: "c_demo_028",
    name: "Ines Ferreira",
    email: "ines@blackhawkx.example",
    company: "Blackhawk X",
    role: "Founder",
    phone: "",
    linkedin: "",
    tags: "founder",
    notes: "Recommended by Tom Becker (Apex Partners).",
    createdAt: D(-1),
    updatedAt: D(-1),
  },
  {
    id: "c_demo_029",
    name: "Bryan Hsu",
    email: "bryan@motoworks.example",
    company: "Motoworks",
    role: "Sales Director",
    phone: "",
    linkedin: "",
    tags: "ICP",
    notes: "Form submission, never opened follow-up.",
    createdAt: D(-2),
    updatedAt: D(-2),
  },
  {
    id: "c_demo_030",
    name: "Aaliyah Brooks",
    email: "aaliyah@verdantgrid.example",
    company: "Verdant Grid",
    role: "VP of Growth",
    phone: "",
    linkedin: "",
    tags: "ICP, replied",
    notes: "Quoted; in legal review.",
    createdAt: D(-22),
    updatedAt: D(-1),
  },
];

export const SEED_LEADS: Lead[] = [
  {
    id: "l_demo_001",
    contactId: "c_demo_001",
    source: "manual",
    stage: "engaged",
    score: 88,
    scoreReason:
      "Decision-maker title at ICP-fit company; replied to opener.",
    value: 36000,
    owner: "you@yourco.example",
    lastContactedAt: D(-2),
    nextActionAt: D(2),
    nextAction: "Send pricing one-pager",
    notes: "",
    createdAt: D(-21),
    updatedAt: D(-2),
  },
  {
    id: "l_demo_002",
    contactId: "c_demo_002",
    source: "linkedin",
    stage: "qualified",
    score: 92,
    scoreReason:
      "Replied within 30 minutes; explicit budget signal in note.",
    value: 24000,
    owner: "you@yourco.example",
    lastContactedAt: D(-1),
    nextActionAt: D(1),
    nextAction: "Demo Tuesday",
    notes: "",
    createdAt: D(-14),
    updatedAt: D(-1),
  },
  {
    id: "l_demo_003",
    contactId: "c_demo_003",
    source: "csv-import",
    stage: "contacted",
    score: 71,
    scoreReason: "Founder at Series A AI startup; outbound-tool ICP.",
    value: 12000,
    owner: "you@yourco.example",
    lastContactedAt: D(-1),
    nextActionAt: D(2),
    nextAction: "Follow-up step 2",
    notes: "",
    createdAt: D(-9),
    updatedAt: D(-1),
  },
  {
    id: "l_demo_004",
    contactId: "c_demo_004",
    source: "referral",
    stage: "won",
    score: 95,
    scoreReason: "Warm referral; closed pilot.",
    value: 18000,
    owner: "you@yourco.example",
    lastContactedAt: D(-3),
    nextActionAt: "",
    nextAction: "",
    notes: "",
    createdAt: D(-7),
    updatedAt: D(-3),
  },
  {
    id: "l_demo_005",
    contactId: "c_demo_005",
    source: "manual",
    stage: "new",
    score: 64,
    scoreReason: "ICP fit, no prior touch.",
    value: 30000,
    owner: "you@yourco.example",
    lastContactedAt: "",
    nextActionAt: D(0),
    nextAction: "First touch",
    notes: "",
    createdAt: D(-5),
    updatedAt: D(-1),
  },
  {
    id: "l_demo_006",
    contactId: "c_demo_006",
    source: "csv-import",
    stage: "new",
    score: 50,
    scoreReason: "Limited profile data.",
    value: 0,
    owner: "you@yourco.example",
    lastContactedAt: "",
    nextActionAt: D(0),
    nextAction: "Score with AI",
    notes: "",
    createdAt: D(-3),
    updatedAt: D(-3),
  },
  {
    id: "l_demo_007",
    contactId: "c_demo_007",
    source: "manual",
    stage: "engaged",
    score: 78,
    scoreReason: "Champion at known account; pre-sold internally.",
    value: 0,
    owner: "you@yourco.example",
    lastContactedAt: D(-2),
    nextActionAt: D(3),
    nextAction: "Send technical brief",
    notes: "",
    createdAt: D(-2),
    updatedAt: D(-2),
  },
  {
    id: "l_demo_008",
    contactId: "c_demo_008",
    source: "form:contact-us",
    stage: "contacted",
    score: 80,
    scoreReason: "Inbound form submission with company + role.",
    value: 15000,
    owner: "you@yourco.example",
    lastContactedAt: D(-1),
    nextActionAt: D(2),
    nextAction: "Sequence step 2",
    notes: "",
    createdAt: D(-1),
    updatedAt: D(-1),
  },
  { id: "l_demo_009", contactId: "c_demo_009", source: "linkedin", stage: "qualified", score: 90, scoreReason: "Series C fintech VP; explicit budget signal.", value: 60000, owner: "you@yourco.example", lastContactedAt: D(-4), nextActionAt: D(1), nextAction: "Send proposal", notes: "", createdAt: D(-30), updatedAt: D(-4) },
  { id: "l_demo_010", contactId: "c_demo_010", source: "inbound", stage: "lost", score: 35, scoreReason: "Went silent post-demo; chose competitor.", value: 0, owner: "you@yourco.example", lastContactedAt: D(-10), nextActionAt: "", nextAction: "", notes: "Re-engage in 6mo", createdAt: D(-25), updatedAt: D(-10) },
  { id: "l_demo_011", contactId: "c_demo_011", source: "sequence:founder", stage: "engaged", score: 86, scoreReason: "Founder replied; asked for ROI math.", value: 18000, owner: "you@yourco.example", lastContactedAt: D(-2), nextActionAt: D(1), nextAction: "Share ROI calculator", notes: "", createdAt: D(-20), updatedAt: D(-2) },
  { id: "l_demo_012", contactId: "c_demo_012", source: "manual", stage: "engaged", score: 84, scoreReason: "RevOps owner at hot account; pre-sold.", value: 0, owner: "you@yourco.example", lastContactedAt: D(-3), nextActionAt: D(2), nextAction: "Technical eval call", notes: "", createdAt: D(-18), updatedAt: D(-3) },
  { id: "l_demo_013", contactId: "c_demo_013", source: "event", stage: "contacted", score: 70, scoreReason: "Met at HIMSS; healthcare ICP.", value: 24000, owner: "you@yourco.example", lastContactedAt: D(-5), nextActionAt: D(2), nextAction: "Send compliance one-pager", notes: "", createdAt: D(-16), updatedAt: D(-5) },
  { id: "l_demo_014", contactId: "c_demo_014", source: "linkedin", stage: "engaged", score: 78, scoreReason: "Replies to short emails; high-intent fintech BizDev.", value: 30000, owner: "you@yourco.example", lastContactedAt: D(-2), nextActionAt: D(3), nextAction: "Draft 50-word follow-up", notes: "", createdAt: D(-15), updatedAt: D(-2) },
  { id: "l_demo_015", contactId: "c_demo_015", source: "manual", stage: "qualified", score: 88, scoreReason: "Will run trial; champion at Brightleaf.", value: 0, owner: "you@yourco.example", lastContactedAt: D(-2), nextActionAt: D(1), nextAction: "Provision trial workspace", notes: "", createdAt: D(-13), updatedAt: D(-2) },
  { id: "l_demo_016", contactId: "c_demo_016", source: "csv-import", stage: "engaged", score: 62, scoreReason: "Replied step 1, ghosted step 2.", value: 12000, owner: "you@yourco.example", lastContactedAt: D(-6), nextActionAt: D(0), nextAction: "Try a different angle", notes: "", createdAt: D(-12), updatedAt: D(-6) },
  { id: "l_demo_017", contactId: "c_demo_017", source: "csv-import", stage: "contacted", score: 48, scoreReason: "Marketing buyer; not direct ICP.", value: 0, owner: "you@yourco.example", lastContactedAt: D(-4), nextActionAt: D(7), nextAction: "Long-term nurture", notes: "", createdAt: D(-11), updatedAt: D(-4) },
  { id: "l_demo_018", contactId: "c_demo_018", source: "linkedin", stage: "lost", score: 30, scoreReason: "Just signed competing tool.", value: 0, owner: "you@yourco.example", lastContactedAt: D(-10), nextActionAt: D(90), nextAction: "Q3 re-engage", notes: "", createdAt: D(-10), updatedAt: D(-1) },
  { id: "l_demo_019", contactId: "c_demo_019", source: "referral", stage: "qualified", score: 91, scoreReason: "Founder, raising — high intent.", value: 12000, owner: "you@yourco.example", lastContactedAt: D(-1), nextActionAt: D(2), nextAction: "Schedule pilot", notes: "", createdAt: D(-9), updatedAt: D(-1) },
  { id: "l_demo_020", contactId: "c_demo_020", source: "event", stage: "contacted", score: 66, scoreReason: "Long sales cycle; needs case study.", value: 36000, owner: "you@yourco.example", lastContactedAt: D(-3), nextActionAt: D(5), nextAction: "Send healthcare case study", notes: "", createdAt: D(-8), updatedAt: D(-3) },
  { id: "l_demo_021", contactId: "c_demo_021", source: "manual", stage: "engaged", score: 72, scoreReason: "Pre-seed founder; tight budget.", value: 6000, owner: "you@yourco.example", lastContactedAt: D(-2), nextActionAt: D(3), nextAction: "Send startup pricing", notes: "", createdAt: D(-6), updatedAt: D(-2) },
  { id: "l_demo_022", contactId: "c_demo_022", source: "form:demo-request", stage: "qualified", score: 93, scoreReason: "Inbound demo request from VP RevOps.", value: 48000, owner: "you@yourco.example", lastContactedAt: D(-1), nextActionAt: D(0), nextAction: "Demo today", notes: "", createdAt: D(-4), updatedAt: D(-1) },
  { id: "l_demo_023", contactId: "c_demo_023", source: "csv-import", stage: "new", score: 40, scoreReason: "Limited profile; needs enrichment.", value: 0, owner: "you@yourco.example", lastContactedAt: "", nextActionAt: D(0), nextAction: "Score with AI", notes: "", createdAt: D(-3), updatedAt: D(-3) },
  { id: "l_demo_024", contactId: "c_demo_024", source: "manual", stage: "engaged", score: 80, scoreReason: "IT champion at hot account.", value: 0, owner: "you@yourco.example", lastContactedAt: D(-2), nextActionAt: D(2), nextAction: "Security review docs", notes: "", createdAt: D(-3), updatedAt: D(-2) },
  { id: "l_demo_025", contactId: "c_demo_025", source: "sequence:mid-market", stage: "engaged", score: 76, scoreReason: "Replied to variant B subject.", value: 30000, owner: "you@yourco.example", lastContactedAt: D(-1), nextActionAt: D(2), nextAction: "Book demo", notes: "", createdAt: D(-2), updatedAt: D(-1) },
  { id: "l_demo_026", contactId: "c_demo_026", source: "form:demo-request", stage: "contacted", score: 82, scoreReason: "Inbound from form.", value: 18000, owner: "you@yourco.example", lastContactedAt: D(-1), nextActionAt: D(1), nextAction: "Confirm demo time", notes: "", createdAt: D(-1), updatedAt: D(-1) },
  { id: "l_demo_027", contactId: "c_demo_027", source: "manual", stage: "new", score: 68, scoreReason: "Q3 procurement signal.", value: 30000, owner: "you@yourco.example", lastContactedAt: "", nextActionAt: D(0), nextAction: "First touch", notes: "", createdAt: D(-1), updatedAt: D(-1) },
  { id: "l_demo_028", contactId: "c_demo_028", source: "referral", stage: "new", score: 78, scoreReason: "Warm referral from existing customer.", value: 12000, owner: "you@yourco.example", lastContactedAt: "", nextActionAt: D(0), nextAction: "Send intro email", notes: "", createdAt: D(-1), updatedAt: D(-1) },
  { id: "l_demo_029", contactId: "c_demo_029", source: "form:contact-us", stage: "lost", score: 25, scoreReason: "Never opened follow-up.", value: 0, owner: "you@yourco.example", lastContactedAt: D(-2), nextActionAt: "", nextAction: "", notes: "", createdAt: D(-2), updatedAt: D(-2) },
  { id: "l_demo_030", contactId: "c_demo_030", source: "manual", stage: "won", score: 96, scoreReason: "Closed; in legal review.", value: 42000, owner: "you@yourco.example", lastContactedAt: D(-1), nextActionAt: "", nextAction: "Kickoff after signature", notes: "", createdAt: D(-22), updatedAt: D(-1) },
];

export const SEED_CAMPAIGNS: Campaign[] = [
  { id: "cmp_demo_001", name: "Q2 mid-market push", goal: "Book 20 demos with VP Sales / RevOps at mid-market companies.", audience: "VP Sales / Head of Sales Ops, 200-2000 employees", status: "active", templateId: "tpl_demo_001", sentCount: 78, repliedCount: 14, createdAt: D(-21) },
  { id: "cmp_demo_002", name: "Founder outreach", goal: "Land 5 design-partner conversations with Series A founders.", audience: "Founders / CEOs, 10-50 employees", status: "active", templateId: "tpl_demo_002", sentCount: 42, repliedCount: 9, createdAt: D(-14) },
  { id: "cmp_demo_003", name: "Healthcare GTM Q2", goal: "Source 3 enterprise healthcare opportunities.", audience: "Heads of GTM at healthcare orgs", status: "active", templateId: "", sentCount: 21, repliedCount: 4, createdAt: D(-12) },
  { id: "cmp_demo_004", name: "Fintech RevOps re-engage", goal: "Re-engage 50 fintech RevOps leaders from last quarter.", audience: "VP RevOps / Sales Ops at fintech 100-1000 employees", status: "paused", templateId: "", sentCount: 50, repliedCount: 6, createdAt: D(-25) },
  { id: "cmp_demo_005", name: "Inbound nurture", goal: "Convert form fills into demos within 14 days.", audience: "Anyone who submits /f/contact-us or /f/demo-request", status: "active", templateId: "", sentCount: 12, repliedCount: 5, createdAt: D(-9) },
];

export const SEED_TEMPLATES: Template[] = [
  {
    id: "tpl_demo_001",
    name: "Mid-market opener",
    subject: "Quick idea for {{company}}",
    body:
      "Hi {{firstName}},\n\nNoticed {{company}} is scaling outbound. " +
      "We help VPs of Sales like you ship 30% more pipeline with AI-personalized sequences.\n\n" +
      "Open to a 15-minute look next week?\n\n— {{senderName}}",
    aiPrompt:
      "Book an intro demo with a VP of Sales at a mid-market company. Reference scaling outbound.",
    createdAt: D(-21),
  },
  {
    id: "tpl_demo_002",
    name: "Founder breakup",
    subject: "Last note for now",
    body:
      "Hi {{firstName}},\n\nI'll stop pinging — but if outbound becomes a priority " +
      "in the next quarter, the offer stands.\n\n— {{senderName}}",
    aiPrompt:
      "Soft breakup email to a founder who has not replied to two prior emails.",
    createdAt: D(-14),
  },
  { id: "tpl_demo_003", name: "Healthcare ICP opener", subject: "Compliance + outbound for {{company}}", body: "Hi {{firstName}},\n\nWe help healthcare GTM teams ship outbound without tripping HIPAA. {{company}} caught my eye — happy to share a redacted case study from a similar org.\n\nWorth 15 minutes?\n\n— {{senderName}}", aiPrompt: "Open conversation with Head of GTM at a healthcare org. Compliance angle.", createdAt: D(-12) },
  { id: "tpl_demo_004", name: "Inbound demo confirmation", subject: "Confirmed: {{company}} demo", body: "Hi {{firstName}},\n\nLooking forward to walking you through it. I'll send a calendar invite for {{date}}; let me know if a different time works.\n\n— {{senderName}}", aiPrompt: "Confirm a demo for an inbound lead. Friendly, brief.", createdAt: D(-9) },
  { id: "tpl_demo_005", name: "Re-engage 90 days", subject: "{{company}} — still on the radar?", body: "Hi {{firstName}},\n\nA lot has changed since we last spoke. New AI sequencing + reply detection — happy to share a quick what's-new.\n\n5 minutes?\n\n— {{senderName}}", aiPrompt: "Re-engage a lead who went cold 90 days ago. Reference product changes.", createdAt: D(-30) },
];

export const SEED_EMAILS: EmailRecord[] = [
  {
    id: "e_demo_001",
    contactId: "c_demo_001",
    campaignId: "cmp_demo_001",
    sequenceEnrollmentId: "",
    stepIndex: "",
    variant: "A",
    subject: "Quick idea for Northwind Logistics",
    body:
      "Hi Maya,\n\nNoticed Northwind is scaling outbound into EU. We help VPs of Sales " +
      "like you ship 30% more pipeline with AI-personalized sequences.\n\n" +
      "Open to a 15-min look next week?\n\n— You",
    sentAt: D(-7),
    status: "sent",
    aiGenerated: "yes",
    prompt: "Book an intro demo with a VP of Sales (mid-market).",
    threadId: "thr_demo_001",
    repliedAt: D(-6),
  },
  {
    id: "e_demo_002",
    contactId: "c_demo_001",
    campaignId: "cmp_demo_001",
    sequenceEnrollmentId: "",
    stepIndex: "",
    variant: "B",
    subject: "EU expansion + outbound — quick thought",
    body:
      "Hi Maya,\n\nFollowing up on the EU expansion — happy to share what's working " +
      "for similar GTM teams. 15 minutes Thursday?\n\n— You",
    sentAt: D(-2),
    status: "sent",
    aiGenerated: "yes",
    prompt: "Re-engage Maya at Northwind on EU expansion angle.",
    threadId: "thr_demo_002",
    repliedAt: "",
  },
  {
    id: "e_demo_003",
    contactId: "c_demo_002",
    campaignId: "cmp_demo_001",
    sequenceEnrollmentId: "",
    stepIndex: "",
    variant: "A",
    subject: "Pipeline analytics for Brightleaf",
    body:
      "Hi Diego,\n\nBrightleaf's growth posts on funnel hygiene caught my eye. " +
      "Curious if you've shopped tooling for outbound conversion reporting?\n\n— You",
    sentAt: D(-3),
    status: "sent",
    aiGenerated: "yes",
    prompt: "Book demo with Diego — angle on funnel analytics.",
    threadId: "thr_demo_003",
    repliedAt: D(-1),
  },
  {
    id: "e_demo_004",
    contactId: "c_demo_003",
    campaignId: "cmp_demo_002",
    sequenceEnrollmentId: "en_demo_001",
    stepIndex: "0",
    variant: "",
    subject: "Outbound tooling for Tidewater",
    body:
      "Hi Priya,\n\nSeries A founder myself once — outbound tooling was always " +
      "the headache. Worth a 15-min compare?\n\n— You",
    sentAt: D(-1),
    status: "sent",
    aiGenerated: "yes",
    prompt: "Book design partner conversation with Series A founder.",
    threadId: "thr_demo_004",
    repliedAt: "",
  },
  {
    id: "e_demo_005",
    contactId: "c_demo_005",
    campaignId: "cmp_demo_001",
    sequenceEnrollmentId: "",
    stepIndex: "",
    variant: "",
    subject: "Helix Sales Ops — quick idea",
    body:
      "Hi Sara,\n\nNoticed Helix is hiring SDRs — usually a sign sales ops is " +
      "thinking about outbound tooling. 10 minutes next week?\n\n— You",
    sentAt: D(-1),
    status: "sent",
    aiGenerated: "yes",
    prompt: "Open conversation with Sales Ops Director at healthcare company.",
    threadId: "thr_demo_005",
    repliedAt: "",
  },
  { id: "e_demo_006", contactId: "c_demo_009", campaignId: "cmp_demo_004", sequenceEnrollmentId: "", stepIndex: "", variant: "A", subject: "Summit Financial — outbound stack?", body: "Hi Hannah,\n\nFintech VPs of Revenue I talk to all hit the same wall around 50 reps: rep-by-rep tooling fragments. Worth a 15-min compare?\n\n— You", sentAt: D(-12), status: "sent", aiGenerated: "yes", prompt: "Re-engage fintech VP Revenue.", threadId: "thr_demo_006", repliedAt: D(-11) },
  { id: "e_demo_007", contactId: "c_demo_009", campaignId: "cmp_demo_004", sequenceEnrollmentId: "", stepIndex: "", variant: "", subject: "Re: Summit Financial — outbound stack?", body: "Hi Hannah,\n\nThanks for the reply. Attached are two pricing scenarios; happy to walk through next week.\n\n— You", sentAt: D(-4), status: "sent", aiGenerated: "no", prompt: "", threadId: "thr_demo_007", repliedAt: "" },
  { id: "e_demo_008", contactId: "c_demo_011", campaignId: "cmp_demo_002", sequenceEnrollmentId: "en_demo_002", stepIndex: "0", variant: "", subject: "Outbound for Orbital", body: "Hi Yuki,\n\nFounders shipping to enterprise tend to wait too long to set up real outbound. Worth a 15-minute compare?\n\n— You", sentAt: D(-15), status: "sent", aiGenerated: "yes", prompt: "Step 1: founder ICP.", threadId: "thr_demo_008", repliedAt: D(-14) },
  { id: "e_demo_009", contactId: "c_demo_011", campaignId: "cmp_demo_002", sequenceEnrollmentId: "en_demo_002", stepIndex: "1", variant: "", subject: "Re: Outbound for Orbital", body: "Hi Yuki,\n\nGreat — here's the ROI math sheet. Numbers are conservative; happy to tweak inputs live.\n\n— You", sentAt: D(-2), status: "sent", aiGenerated: "yes", prompt: "Reply with ROI math.", threadId: "thr_demo_009", repliedAt: "" },
  { id: "e_demo_010", contactId: "c_demo_012", campaignId: "cmp_demo_001", sequenceEnrollmentId: "", stepIndex: "", variant: "B", subject: "Carlos — RevOps tooling for Northwind", body: "Hi Carlos,\n\nMaya mentioned you own RevOps tooling. We help VPs save ~6 hrs/week per rep on outbound logistics. Quick compare?\n\n— You", sentAt: D(-3), status: "sent", aiGenerated: "yes", prompt: "Mid-market RevOps.", threadId: "thr_demo_010", repliedAt: D(-2) },
  { id: "e_demo_011", contactId: "c_demo_013", campaignId: "cmp_demo_003", sequenceEnrollmentId: "", stepIndex: "", variant: "A", subject: "Compliance + outbound for Bluepine", body: "Hi Esther,\n\nMet briefly at HIMSS. We help healthcare GTM teams ship outbound without tripping HIPAA. Worth 15?\n\n— You", sentAt: D(-5), status: "sent", aiGenerated: "yes", prompt: "Healthcare GTM ICP.", threadId: "thr_demo_011", repliedAt: "" },
  { id: "e_demo_012", contactId: "c_demo_014", campaignId: "cmp_demo_004", sequenceEnrollmentId: "", stepIndex: "", variant: "B", subject: "Wei — 50 words", body: "Hi Wei,\n\nQuanta hiring 4 SDRs = outbound stack moment. We help teams like yours ship 30% more pipeline. 50 words. Open to a chat?\n\n— You", sentAt: D(-8), status: "sent", aiGenerated: "yes", prompt: "Short subject for async-first prospect.", threadId: "thr_demo_012", repliedAt: D(-2) },
  { id: "e_demo_013", contactId: "c_demo_015", campaignId: "cmp_demo_001", sequenceEnrollmentId: "", stepIndex: "", variant: "A", subject: "Brightleaf trial setup", body: "Hi Lena,\n\nDiego said you'd be running point on the trial. Want to set up a 15-min onboarding once you're ready?\n\n— You", sentAt: D(-2), status: "sent", aiGenerated: "no", prompt: "", threadId: "thr_demo_013", repliedAt: "" },
  { id: "e_demo_014", contactId: "c_demo_016", campaignId: "cmp_demo_001", sequenceEnrollmentId: "en_demo_003", stepIndex: "0", variant: "", subject: "Gridworks — outbound idea", body: "Hi Marcus,\n\nGridworks scaling outbound — usually a sign tooling is up for review. 15 minutes?\n\n— You", sentAt: D(-9), status: "sent", aiGenerated: "yes", prompt: "Mid-market opener step 1.", threadId: "thr_demo_014", repliedAt: D(-8) },
  { id: "e_demo_015", contactId: "c_demo_016", campaignId: "cmp_demo_001", sequenceEnrollmentId: "en_demo_003", stepIndex: "1", variant: "", subject: "Re: Gridworks — outbound idea", body: "Hi Marcus,\n\nDifferent angle — three customers like you cut SDR ramp time in half. Worth a look?\n\n— You", sentAt: D(-6), status: "sent", aiGenerated: "yes", prompt: "Step 2: different angle.", threadId: "thr_demo_015", repliedAt: "" },
  { id: "e_demo_016", contactId: "c_demo_018", campaignId: "cmp_demo_004", sequenceEnrollmentId: "", stepIndex: "", variant: "A", subject: "Stride TX — Q3 check-in", body: "Hi Olu,\n\nQ3 is when stack reviews happen — happy to send a what's-new doc if useful.\n\n— You", sentAt: D(-10), status: "sent", aiGenerated: "yes", prompt: "Re-engage 90-days-cold lead.", threadId: "thr_demo_016", repliedAt: D(-9) },
  { id: "e_demo_017", contactId: "c_demo_019", campaignId: "cmp_demo_002", sequenceEnrollmentId: "", stepIndex: "", variant: "B", subject: "Ravi — pilot offer", body: "Hi Ravi,\n\nMeadowlark in raise mode = perfect time to lock outbound process. Free pilot for funded startups; interested?\n\n— You", sentAt: D(-1), status: "sent", aiGenerated: "yes", prompt: "Founder pilot offer.", threadId: "thr_demo_017", repliedAt: "" },
  { id: "e_demo_018", contactId: "c_demo_020", campaignId: "cmp_demo_003", sequenceEnrollmentId: "", stepIndex: "", variant: "A", subject: "Ridgeline — case study", body: "Hi Kira,\n\nAttaching a redacted case study from a Bio org we work with. Numbers should look familiar.\n\n— You", sentAt: D(-3), status: "sent", aiGenerated: "no", prompt: "", threadId: "thr_demo_018", repliedAt: "" },
  { id: "e_demo_019", contactId: "c_demo_021", campaignId: "cmp_demo_002", sequenceEnrollmentId: "", stepIndex: "", variant: "B", subject: "Pivotgear — startup price", body: "Hi Drew,\n\nWe have startup pricing for pre-seed + seed teams. 15-min walk-through?\n\n— You", sentAt: D(-2), status: "sent", aiGenerated: "yes", prompt: "Pre-seed founder pricing.", threadId: "thr_demo_019", repliedAt: "" },
  { id: "e_demo_020", contactId: "c_demo_022", campaignId: "cmp_demo_005", sequenceEnrollmentId: "", stepIndex: "", variant: "", subject: "Vellum Pay — confirmed", body: "Hi Amara,\n\nThanks for the demo request. Sending a calendar invite for Thursday 10am PT — does that work?\n\n— You", sentAt: D(-1), status: "sent", aiGenerated: "no", prompt: "", threadId: "thr_demo_020", repliedAt: "" },
  { id: "e_demo_021", contactId: "c_demo_025", campaignId: "cmp_demo_001", sequenceEnrollmentId: "", stepIndex: "", variant: "A", subject: "Coppergate — quick idea", body: "Hi Patrick,\n\nNoticed Coppergate scaling — we help VPs ship more pipeline. 15 minutes?\n\n— You", sentAt: D(-4), status: "sent", aiGenerated: "yes", prompt: "Mid-market opener.", threadId: "thr_demo_021", repliedAt: "" },
  { id: "e_demo_022", contactId: "c_demo_025", campaignId: "cmp_demo_001", sequenceEnrollmentId: "", stepIndex: "", variant: "B", subject: "Patrick — 30% more pipeline?", body: "Hi Patrick,\n\nFollow-up: we've helped 5 VPs add 30% more pipeline last quarter. Open to a chat?\n\n— You", sentAt: D(-2), status: "sent", aiGenerated: "yes", prompt: "Mid-market re-attempt with stronger subject.", threadId: "thr_demo_022", repliedAt: D(-1) },
  { id: "e_demo_023", contactId: "c_demo_026", campaignId: "cmp_demo_005", sequenceEnrollmentId: "", stepIndex: "", variant: "", subject: "Firstwave — demo confirm", body: "Hi Mei,\n\nThanks for the demo request. Tuesday 2pm PT work?\n\n— You", sentAt: D(-1), status: "sent", aiGenerated: "no", prompt: "", threadId: "thr_demo_023", repliedAt: "" },
  { id: "e_demo_024", contactId: "c_demo_028", campaignId: "cmp_demo_002", sequenceEnrollmentId: "", stepIndex: "", variant: "", subject: "Intro from Tom Becker", body: "Hi Ines,\n\nTom Becker put us in touch. Quick chat about Blackhawk's GTM next week?\n\n— You", sentAt: D(0), status: "draft", aiGenerated: "no", prompt: "", threadId: "", repliedAt: "" },
  { id: "e_demo_025", contactId: "c_demo_030", campaignId: "cmp_demo_001", sequenceEnrollmentId: "", stepIndex: "", variant: "A", subject: "Verdant Grid — kickoff", body: "Hi Aaliyah,\n\nFinal contract is in your inbox. Once signed, we'll schedule a kickoff.\n\n— You", sentAt: D(-1), status: "sent", aiGenerated: "no", prompt: "", threadId: "thr_demo_025", repliedAt: "" },
  { id: "e_demo_026", contactId: "c_demo_002", campaignId: "cmp_demo_005", sequenceEnrollmentId: "", stepIndex: "", variant: "", subject: "Demo Tuesday 11am PT — Brightleaf", body: "Hi Diego,\n\nLooking forward to it. Sending an invite now.\n\n— You", sentAt: D(-1), status: "sent", aiGenerated: "no", prompt: "", threadId: "thr_demo_026", repliedAt: "" },
  { id: "e_demo_027", contactId: "c_demo_007", campaignId: "cmp_demo_001", sequenceEnrollmentId: "", stepIndex: "", variant: "B", subject: "Aiko — technical brief", body: "Hi Aiko,\n\nMaya asked me to loop you in on the technical side. Attaching a 2-pager — happy to walk through.\n\n— You", sentAt: D(-2), status: "sent", aiGenerated: "yes", prompt: "Champion enablement.", threadId: "thr_demo_027", repliedAt: "" },
];

export const SEED_TASKS: Task[] = [
  {
    id: "t_demo_001",
    contactId: "c_demo_001",
    title: "Send pricing one-pager",
    dueAt: D(2).slice(0, 10),
    status: "open",
    owner: "you@yourco.example",
    notes: "Maya asked for it on the call.",
    createdAt: D(-2),
    completedAt: "",
  },
  {
    id: "t_demo_002",
    contactId: "c_demo_002",
    title: "Demo with Diego (Tuesday 11am PT)",
    dueAt: D(1).slice(0, 10),
    status: "open",
    owner: "you@yourco.example",
    notes: "",
    createdAt: D(-1),
    completedAt: "",
  },
  {
    id: "t_demo_003",
    contactId: "c_demo_005",
    title: "Loop in IT contact at Helix",
    dueAt: D(0).slice(0, 10),
    status: "open",
    owner: "you@yourco.example",
    notes: "Procurement gate is RevOps; we need an IT champion too.",
    createdAt: D(-1),
    completedAt: "",
  },
  {
    id: "t_demo_004",
    contactId: "c_demo_004",
    title: "Schedule kickoff with Apex",
    dueAt: D(-1).slice(0, 10),
    status: "done",
    owner: "you@yourco.example",
    notes: "",
    createdAt: D(-3),
    completedAt: D(-1),
  },
  { id: "t_demo_005", contactId: "c_demo_009", title: "Send Summit Financial proposal", dueAt: D(1).slice(0, 10), status: "open", owner: "you@yourco.example", notes: "Two pricing tiers — annual + monthly.", createdAt: D(-2), completedAt: "" },
  { id: "t_demo_006", contactId: "c_demo_011", title: "Share ROI calculator with Yuki", dueAt: D(1).slice(0, 10), status: "open", owner: "you@yourco.example", notes: "", createdAt: D(-1), completedAt: "" },
  { id: "t_demo_007", contactId: "c_demo_013", title: "Send compliance one-pager to Esther", dueAt: D(2).slice(0, 10), status: "open", owner: "you@yourco.example", notes: "HIPAA + SOC2 highlights.", createdAt: D(-3), completedAt: "" },
  { id: "t_demo_008", contactId: "c_demo_015", title: "Provision Brightleaf trial workspace", dueAt: D(0).slice(0, 10), status: "open", owner: "you@yourco.example", notes: "", createdAt: D(-1), completedAt: "" },
  { id: "t_demo_009", contactId: "c_demo_019", title: "Schedule Meadowlark pilot", dueAt: D(2).slice(0, 10), status: "open", owner: "you@yourco.example", notes: "", createdAt: D(-1), completedAt: "" },
  { id: "t_demo_010", contactId: "c_demo_020", title: "Send Bio case study to Kira", dueAt: D(5).slice(0, 10), status: "open", owner: "you@yourco.example", notes: "", createdAt: D(-2), completedAt: "" },
  { id: "t_demo_011", contactId: "c_demo_022", title: "Vellum Pay demo (Thursday 10am PT)", dueAt: D(0).slice(0, 10), status: "open", owner: "you@yourco.example", notes: "Inbound — high intent.", createdAt: D(-1), completedAt: "" },
  { id: "t_demo_012", contactId: "c_demo_023", title: "AI-score Henrik (CSV import)", dueAt: D(0).slice(0, 10), status: "open", owner: "you@yourco.example", notes: "", createdAt: D(-1), completedAt: "" },
  { id: "t_demo_013", contactId: "c_demo_024", title: "Send security review docs to Elena", dueAt: D(2).slice(0, 10), status: "open", owner: "you@yourco.example", notes: "SOC2 + pen-test summary.", createdAt: D(-1), completedAt: "" },
  { id: "t_demo_014", contactId: "c_demo_028", title: "Intro email to Ines (referred by Tom)", dueAt: D(1).slice(0, 10), status: "open", owner: "you@yourco.example", notes: "", createdAt: D(0), completedAt: "" },
  { id: "t_demo_015", contactId: "c_demo_030", title: "Verdant Grid kickoff post-signature", dueAt: D(7).slice(0, 10), status: "open", owner: "you@yourco.example", notes: "", createdAt: D(-1), completedAt: "" },
  { id: "t_demo_016", contactId: "c_demo_006", title: "Enrich Liam's profile (CSV import)", dueAt: D(-2).slice(0, 10), status: "done", owner: "you@yourco.example", notes: "", createdAt: D(-3), completedAt: D(-2) },
  { id: "t_demo_017", contactId: "c_demo_002", title: "Demo with Diego (Tuesday 11am PT)", dueAt: D(-3).slice(0, 10), status: "done", owner: "you@yourco.example", notes: "Went great — moving to qualified.", createdAt: D(-5), completedAt: D(-3) },
];

export const SEED_ACTIVITY: Activity[] = [
  {
    id: "a_demo_001",
    contactId: "c_demo_001",
    type: "email_sent",
    summary: "Sent: Quick idea for Northwind Logistics",
    meta: '{"variant":"A"}',
    createdAt: D(-7),
    actor: "you@yourco.example",
  },
  {
    id: "a_demo_002",
    contactId: "c_demo_001",
    type: "email_replied",
    summary: "Reply received: Quick idea for Northwind Logistics",
    meta: "",
    createdAt: D(-6),
    actor: "you@yourco.example",
  },
  {
    id: "a_demo_003",
    contactId: "c_demo_001",
    type: "stage_change",
    summary: "Stage: contacted → engaged (reply detected)",
    meta: "",
    createdAt: D(-6),
    actor: "you@yourco.example",
  },
  {
    id: "a_demo_004",
    contactId: "c_demo_001",
    type: "score_updated",
    summary: "AI score: 88 — Decision-maker title at ICP-fit company; replied to opener.",
    meta: '{"score":88}',
    createdAt: D(-2),
    actor: "you@yourco.example",
  },
  {
    id: "a_demo_005",
    contactId: "c_demo_002",
    type: "email_sent",
    summary: "Sent: Pipeline analytics for Brightleaf",
    meta: "",
    createdAt: D(-3),
    actor: "you@yourco.example",
  },
  {
    id: "a_demo_006",
    contactId: "c_demo_002",
    type: "email_replied",
    summary: "Reply received: Pipeline analytics for Brightleaf",
    meta: "",
    createdAt: D(-1),
    actor: "you@yourco.example",
  },
  {
    id: "a_demo_007",
    contactId: "c_demo_002",
    type: "stage_change",
    summary: "Stage: contacted → qualified",
    meta: "",
    createdAt: D(-1),
    actor: "you@yourco.example",
  },
  {
    id: "a_demo_008",
    contactId: "c_demo_003",
    type: "sequence_enrolled",
    summary: "Enrolled in sequence",
    meta: '{"sequenceId":"seq_demo_001"}',
    createdAt: D(-1),
    actor: "you@yourco.example",
  },
  {
    id: "a_demo_009",
    contactId: "c_demo_003",
    type: "email_sent",
    summary: "Sequence step 1: Outbound tooling for Tidewater",
    meta: "",
    createdAt: D(-1),
    actor: "you@yourco.example",
  },
  {
    id: "a_demo_010",
    contactId: "c_demo_008",
    type: "form_submission",
    summary: "Form: Contact us",
    meta: '{"slug":"contact-us"}',
    createdAt: D(-1),
    actor: "form",
  },
  { id: "a_demo_011", contactId: "c_demo_009", type: "email_sent", summary: "Sent: Summit Financial — outbound stack?", meta: "", createdAt: D(-12), actor: "you@yourco.example" },
  { id: "a_demo_012", contactId: "c_demo_009", type: "email_replied", summary: "Reply received: Summit Financial — outbound stack?", meta: "", createdAt: D(-11), actor: "you@yourco.example" },
  { id: "a_demo_013", contactId: "c_demo_009", type: "stage_change", summary: "Stage: contacted → engaged (reply detected)", meta: "", createdAt: D(-11), actor: "you@yourco.example" },
  { id: "a_demo_014", contactId: "c_demo_009", type: "stage_change", summary: "Stage: engaged → qualified", meta: "", createdAt: D(-4), actor: "you@yourco.example" },
  { id: "a_demo_015", contactId: "c_demo_009", type: "task_created", summary: "Task: Send Summit Financial proposal", meta: "", createdAt: D(-2), actor: "you@yourco.example" },
  { id: "a_demo_016", contactId: "c_demo_011", type: "sequence_enrolled", summary: "Enrolled in sequence", meta: '{"sequenceId":"seq_demo_001"}', createdAt: D(-15), actor: "you@yourco.example" },
  { id: "a_demo_017", contactId: "c_demo_011", type: "email_sent", summary: "Sequence step 1: Outbound for Orbital", meta: "", createdAt: D(-15), actor: "you@yourco.example" },
  { id: "a_demo_018", contactId: "c_demo_011", type: "email_replied", summary: "Reply received: Outbound for Orbital", meta: "", createdAt: D(-14), actor: "you@yourco.example" },
  { id: "a_demo_019", contactId: "c_demo_011", type: "sequence_stopped", summary: "Sequence stopped: prospect replied", meta: "", createdAt: D(-14), actor: "you@yourco.example" },
  { id: "a_demo_020", contactId: "c_demo_011", type: "score_updated", summary: "AI score: 86 — Founder replied; asked for ROI math.", meta: '{"score":86}', createdAt: D(-2), actor: "you@yourco.example" },
  { id: "a_demo_021", contactId: "c_demo_012", type: "email_sent", summary: "Sent: Carlos — RevOps tooling for Northwind", meta: '{"variant":"B"}', createdAt: D(-3), actor: "you@yourco.example" },
  { id: "a_demo_022", contactId: "c_demo_012", type: "email_replied", summary: "Reply received: Carlos — RevOps tooling for Northwind", meta: "", createdAt: D(-2), actor: "you@yourco.example" },
  { id: "a_demo_023", contactId: "c_demo_013", type: "email_sent", summary: "Sent: Compliance + outbound for Bluepine", meta: '{"variant":"A"}', createdAt: D(-5), actor: "you@yourco.example" },
  { id: "a_demo_024", contactId: "c_demo_014", type: "email_sent", summary: "Sent: Wei — 50 words", meta: '{"variant":"B"}', createdAt: D(-8), actor: "you@yourco.example" },
  { id: "a_demo_025", contactId: "c_demo_014", type: "email_replied", summary: "Reply received: Wei — 50 words", meta: "", createdAt: D(-2), actor: "you@yourco.example" },
  { id: "a_demo_026", contactId: "c_demo_015", type: "stage_change", summary: "Stage: contacted → qualified", meta: "", createdAt: D(-2), actor: "you@yourco.example" },
  { id: "a_demo_027", contactId: "c_demo_016", type: "sequence_enrolled", summary: "Enrolled in sequence", meta: '{"sequenceId":"seq_demo_002"}', createdAt: D(-9), actor: "you@yourco.example" },
  { id: "a_demo_028", contactId: "c_demo_016", type: "email_sent", summary: "Sequence step 1: Gridworks — outbound idea", meta: "", createdAt: D(-9), actor: "you@yourco.example" },
  { id: "a_demo_029", contactId: "c_demo_016", type: "email_replied", summary: "Reply received: Gridworks — outbound idea", meta: "", createdAt: D(-8), actor: "you@yourco.example" },
  { id: "a_demo_030", contactId: "c_demo_016", type: "email_sent", summary: "Sequence step 2: Re: Gridworks — outbound idea", meta: "", createdAt: D(-6), actor: "you@yourco.example" },
  { id: "a_demo_031", contactId: "c_demo_018", type: "email_sent", summary: "Sent: Stride TX — Q3 check-in", meta: "", createdAt: D(-10), actor: "you@yourco.example" },
  { id: "a_demo_032", contactId: "c_demo_018", type: "email_replied", summary: "Reply received: Stride TX — Q3 check-in", meta: "", createdAt: D(-9), actor: "you@yourco.example" },
  { id: "a_demo_033", contactId: "c_demo_019", type: "email_sent", summary: "Sent: Ravi — pilot offer", meta: '{"variant":"B"}', createdAt: D(-1), actor: "you@yourco.example" },
  { id: "a_demo_034", contactId: "c_demo_022", type: "form_submission", summary: "Form: Request a demo", meta: '{"slug":"demo-request"}', createdAt: D(-4), actor: "form" },
  { id: "a_demo_035", contactId: "c_demo_022", type: "task_created", summary: "Task: Vellum Pay demo (Thursday 10am PT)", meta: "", createdAt: D(-1), actor: "you@yourco.example" },
  { id: "a_demo_036", contactId: "c_demo_025", type: "email_sent", summary: "Sent: Coppergate — quick idea", meta: '{"variant":"A"}', createdAt: D(-4), actor: "you@yourco.example" },
  { id: "a_demo_037", contactId: "c_demo_025", type: "email_sent", summary: "Sent: Patrick — 30% more pipeline?", meta: '{"variant":"B"}', createdAt: D(-2), actor: "you@yourco.example" },
  { id: "a_demo_038", contactId: "c_demo_025", type: "email_replied", summary: "Reply received: Patrick — 30% more pipeline?", meta: '{"variant":"B"}', createdAt: D(-1), actor: "you@yourco.example" },
  { id: "a_demo_039", contactId: "c_demo_025", type: "stage_change", summary: "Stage: contacted → engaged (reply detected)", meta: "", createdAt: D(-1), actor: "you@yourco.example" },
  { id: "a_demo_040", contactId: "c_demo_026", type: "form_submission", summary: "Form: Request a demo", meta: '{"slug":"demo-request"}', createdAt: D(-1), actor: "form" },
  { id: "a_demo_041", contactId: "c_demo_028", type: "note", summary: "Referral from Tom Becker", meta: "", createdAt: D(-1), actor: "you@yourco.example" },
  { id: "a_demo_042", contactId: "c_demo_030", type: "stage_change", summary: "Stage: qualified → won", meta: "", createdAt: D(-7), actor: "you@yourco.example" },
  { id: "a_demo_043", contactId: "c_demo_011", type: "note", summary: "@[You (Demo)] Yuki asked about ROI — can you send the calculator?", meta: "", createdAt: D(-1), actor: "alex@yourco.example" },
  { id: "a_demo_044", contactId: "c_demo_022", type: "note", summary: "@[Alex Rivera] handing Vellum Pay to you — they're hot.", meta: "", createdAt: D(-1), actor: "you@yourco.example" },
];

export const SEED_SEQUENCES: Sequence[] = [
  { id: "seq_demo_001", name: "Founder 3-touch", goal: "Land design-partner conversations with Series A founders.", tone: "warm, direct, peer-to-peer", status: "active", createdAt: D(-14) },
  { id: "seq_demo_002", name: "Mid-market 4-step", goal: "Book demos with VPs Sales / RevOps at 200-2000 employee companies.", tone: "warm, direct, professional", status: "active", createdAt: D(-21) },
  { id: "seq_demo_003", name: "Cold re-engage 90d", goal: "Re-warm leads who went cold 60-120 days ago.", tone: "friendly, no-pressure", status: "paused", createdAt: D(-30) },
];

// Existing seed rows omit the newer multi-channel/A-B/conditions columns;
// undefined values render as empty strings via the demo store, matching
// real Sheets behavior. Cast to suppress strict-field checks.
export const SEED_SEQUENCE_STEPS: SequenceStep[] = ([
  {
    id: "step_demo_001",
    sequenceId: "seq_demo_001",
    stepIndex: "0",
    delayDays: "0",
    subjectHint: "Quick intro",
    instructions: "Open. Reference recent funding or hiring signal.",
    createdAt: D(-14),
  },
  {
    id: "step_demo_002",
    sequenceId: "seq_demo_001",
    stepIndex: "1",
    delayDays: "3",
    subjectHint: "Following up",
    instructions: "Different angle. Share a customer outcome.",
    createdAt: D(-14),
  },
  {
    id: "step_demo_003",
    sequenceId: "seq_demo_001",
    stepIndex: "2",
    delayDays: "5",
    subjectHint: "Last note for now",
    instructions: "Soft breakup. Leave the door open.",
    createdAt: D(-14),
  },
  { id: "step_demo_004", sequenceId: "seq_demo_002", stepIndex: "0", delayDays: "0", subjectHint: "Quick idea", instructions: "Open with a relevant signal (hiring, expansion, funding).", createdAt: D(-21) },
  { id: "step_demo_005", sequenceId: "seq_demo_002", stepIndex: "1", delayDays: "3", subjectHint: "Different angle", instructions: "Lead with a customer outcome metric.", createdAt: D(-21) },
  { id: "step_demo_006", sequenceId: "seq_demo_002", stepIndex: "2", delayDays: "5", subjectHint: "Bumping this up", instructions: "Short, one question.", createdAt: D(-21) },
  { id: "step_demo_007", sequenceId: "seq_demo_002", stepIndex: "3", delayDays: "7", subjectHint: "Last note for now", instructions: "Soft breakup.", createdAt: D(-21) },
  { id: "step_demo_008", sequenceId: "seq_demo_003", stepIndex: "0", delayDays: "0", subjectHint: "Still on the radar?", instructions: "Reference what's new since last contact.", createdAt: D(-30) },
  { id: "step_demo_009", sequenceId: "seq_demo_003", stepIndex: "1", delayDays: "5", subjectHint: "Quick what's-new", instructions: "Bullet list of recent product changes.", createdAt: D(-30) },
] as Partial<SequenceStep>[]) as SequenceStep[];

export const SEED_ENROLLMENTS: Enrollment[] = [
  { id: "en_demo_001", sequenceId: "seq_demo_001", contactId: "c_demo_003", status: "active", currentStep: "1", nextRunAt: D(2), lastRunAt: D(-1), createdAt: D(-1), stoppedReason: "" },
  { id: "en_demo_002", sequenceId: "seq_demo_001", contactId: "c_demo_011", status: "stopped", currentStep: "1", nextRunAt: "", lastRunAt: D(-2), createdAt: D(-15), stoppedReason: "reply_received" },
  { id: "en_demo_003", sequenceId: "seq_demo_002", contactId: "c_demo_016", status: "active", currentStep: "1", nextRunAt: D(0), lastRunAt: D(-6), createdAt: D(-9), stoppedReason: "" },
  { id: "en_demo_004", sequenceId: "seq_demo_002", contactId: "c_demo_021", status: "active", currentStep: "1", nextRunAt: D(1), lastRunAt: D(-2), createdAt: D(-2), stoppedReason: "" },
  { id: "en_demo_005", sequenceId: "seq_demo_001", contactId: "c_demo_019", status: "active", currentStep: "0", nextRunAt: D(2), lastRunAt: D(-1), createdAt: D(-1), stoppedReason: "" },
  { id: "en_demo_006", sequenceId: "seq_demo_002", contactId: "c_demo_025", status: "completed", currentStep: "4", nextRunAt: "", lastRunAt: D(-1), createdAt: D(-12), stoppedReason: "" },
  { id: "en_demo_007", sequenceId: "seq_demo_003", contactId: "c_demo_018", status: "stopped", currentStep: "0", nextRunAt: "", lastRunAt: D(-9), createdAt: D(-10), stoppedReason: "reply_received" },
];

export const SEED_COMPANIES: Company[] = [
  { id: "co_demo_001", name: "Northwind Logistics", domain: "northwind.example", industry: "Logistics", size: "500-1000", website: "https://northwind.example", notes: "Mid-market; expanding to EU.", createdAt: D(-21), updatedAt: D(-2) },
  { id: "co_demo_002", name: "Brightleaf Analytics", domain: "brightleaf.example", industry: "Analytics SaaS", size: "100-200", website: "", notes: "Trial in progress.", createdAt: D(-14), updatedAt: D(-2) },
  { id: "co_demo_003", name: "Summit Financial", domain: "summitfin.example", industry: "Fintech", size: "200-500", website: "", notes: "Series C; in proposal phase.", createdAt: D(-30), updatedAt: D(-4) },
  { id: "co_demo_004", name: "Helix Medical", domain: "helixmed.example", industry: "Healthcare", size: "1000+", website: "", notes: "Multi-stakeholder; champions in Sales Ops + IT.", createdAt: D(-5), updatedAt: D(-2) },
  { id: "co_demo_005", name: "Orbital OS", domain: "orbital-os.example", industry: "Dev tools", size: "10-50", website: "", notes: "Founder-led, ROI-driven evaluation.", createdAt: D(-20), updatedAt: D(-2) },
  { id: "co_demo_006", name: "Verdant Grid", domain: "verdantgrid.example", industry: "Climate tech", size: "100-200", website: "", notes: "Closed; in legal review.", createdAt: D(-22), updatedAt: D(-1) },
];

export const SEED_FORMS: FormDef[] = [
  {
    id: "f_demo_001",
    slug: "contact-us",
    name: "Contact us",
    fields: '["name","email","company","role","notes"]',
    redirectUrl: "",
    tags: "form",
    sequenceId: "",
    createdAt: D(-9),
  },
  {
    id: "f_demo_002",
    slug: "demo-request",
    name: "Request a demo",
    fields: '["name","email","company","role"]',
    redirectUrl: "",
    tags: "demo-request",
    sequenceId: "seq_demo_001",
    createdAt: D(-7),
  },
  { id: "f_demo_003", slug: "investor-intro", name: "Investor intro request", fields: '["name","email","company","role","notes"]', redirectUrl: "", tags: "investor", sequenceId: "", createdAt: D(-5) },
  { id: "f_demo_004", slug: "partner-program", name: "Partner program signup", fields: '["name","email","company","notes"]', redirectUrl: "", tags: "partner", sequenceId: "seq_demo_002", createdAt: D(-3) },
];

export const SEED_TAGS: TagDef[] = [
  { id: "tg_demo_001", name: "ICP", color: "leo", createdAt: D(-30) },
  { id: "tg_demo_002", name: "fintech", color: "sky", createdAt: D(-30) },
  { id: "tg_demo_003", name: "healthcare", color: "emerald", createdAt: D(-30) },
  { id: "tg_demo_004", name: "founder", color: "violet", createdAt: D(-30) },
  { id: "tg_demo_005", name: "champion", color: "amber", createdAt: D(-30) },
  { id: "tg_demo_006", name: "replied", color: "rose", createdAt: D(-30) },
  { id: "tg_demo_007", name: "investor", color: "fuchsia", createdAt: D(-30) },
  { id: "tg_demo_008", name: "marketing", color: "orange", createdAt: D(-30) },
];

export const SEED_AUTOMATIONS: Automation[] = [
  { id: "au_demo_001", name: "High score → create task", trigger: "score_threshold", condition: '{"min":80}', action: "create_task", config: '{"title":"AI scored 80+ — reach out today","dueOffsetDays":0}', active: "yes", createdAt: D(-30) },
  { id: "au_demo_002", name: "Form: demo-request → enroll in Founder seq", trigger: "form_submitted", condition: '{"slug":"demo-request"}', action: "enroll_sequence", config: '{"sequenceId":"seq_demo_001"}', active: "yes", createdAt: D(-21) },
  { id: "au_demo_003", name: "Won deal → notify Slack", trigger: "deal_stage_changed", condition: '{"stage":"won"}', action: "webhook", config: '{"webhookId":"wh_demo_001","template":":tada: {{deal.name}} won — ${{deal.value}}"}', active: "yes", createdAt: D(-14) },
  { id: "au_demo_004", name: "Reply received → bump score", trigger: "email_replied", condition: "{}", action: "bump_score", config: '{"delta":10}', active: "no", createdAt: D(-7) },
];

export const SEED_WEBHOOKS: Webhook[] = [
  { id: "wh_demo_001", name: "Slack #revenue", url: "https://hooks.slack.example/T0/B0/X", events: "deal_won,deal_lost,email_replied", secret: "shh_demo_secret", active: "yes", createdAt: D(-21) },
  { id: "wh_demo_002", name: "Internal notifier", url: "https://api.yourco.example/leocrm/hook", events: "form_submitted", secret: "", active: "yes", createdAt: D(-14) },
];

export const SEED_TOKENS: ApiToken[] = [
  { id: "tok_demo_001", name: "Zapier", memberId: "m_demo_001", token: "leo_pk_demo_z9q3v7tx", createdAt: D(-21), lastUsedAt: D(-1) },
  { id: "tok_demo_002", name: "Internal cron", memberId: "m_demo_001", token: "leo_pk_demo_8h4ku2vl", createdAt: D(-14), lastUsedAt: D(-3) },
];

export const SEED_MEETINGS: Meeting[] = [
  { id: "mt_demo_001", slug: "you-15min", memberId: "m_demo_001", title: "15-min intro", duration: "15", availability: "Tue,Wed,Thu 10-12", active: "yes", createdAt: D(-30) },
  { id: "mt_demo_002", slug: "you-30min", memberId: "m_demo_001", title: "30-min demo", duration: "30", availability: "Mon-Fri 14-17", active: "yes", createdAt: D(-21) },
  { id: "mt_demo_003", slug: "alex-15min", memberId: "m_demo_002", title: "Alex: 15-min", duration: "15", availability: "Mon-Fri 9-12 ET", active: "yes", createdAt: D(-14) },
];

export const SEED_EMAIL_EVENTS: EmailEvent[] = [
  { id: "ee_demo_001", emailId: "e_demo_001", type: "open", url: "", ip: "—", userAgent: "Apple Mail", createdAt: D(-7) },
  { id: "ee_demo_002", emailId: "e_demo_001", type: "click", url: "https://yourco.example/demo", ip: "—", userAgent: "Apple Mail", createdAt: D(-7) },
  { id: "ee_demo_003", emailId: "e_demo_003", type: "open", url: "", ip: "—", userAgent: "Gmail Mobile", createdAt: D(-3) },
  { id: "ee_demo_004", emailId: "e_demo_003", type: "open", url: "", ip: "—", userAgent: "Gmail Web", createdAt: D(-2) },
  { id: "ee_demo_005", emailId: "e_demo_006", type: "open", url: "", ip: "—", userAgent: "Outlook", createdAt: D(-12) },
  { id: "ee_demo_006", emailId: "e_demo_010", type: "open", url: "", ip: "—", userAgent: "Apple Mail", createdAt: D(-3) },
  { id: "ee_demo_007", emailId: "e_demo_010", type: "click", url: "https://yourco.example/case-study", ip: "—", userAgent: "Apple Mail", createdAt: D(-3) },
  { id: "ee_demo_008", emailId: "e_demo_014", type: "open", url: "", ip: "—", userAgent: "Gmail Web", createdAt: D(-9) },
  { id: "ee_demo_009", emailId: "e_demo_022", type: "open", url: "", ip: "—", userAgent: "Apple Mail", createdAt: D(-2) },
  { id: "ee_demo_010", emailId: "e_demo_022", type: "click", url: "https://yourco.example/pricing", ip: "—", userAgent: "Apple Mail", createdAt: D(-2) },
  { id: "ee_demo_011", emailId: "e_demo_004", type: "open", url: "", ip: "—", userAgent: "Gmail Web", createdAt: D(-1) },
];

export const SEED_SCHEDULED: ScheduledEmail[] = [
  { id: "se_demo_001", contactId: "c_demo_017", to: "sofia@palette-co.example", subject: "Quick idea for Palette", body: "Hi Sofia,\n\nFollow-up on Q3 nurture flow.\n\n— You", scheduledFor: D(2), status: "scheduled", createdAt: D(-1), sentAt: "" },
  { id: "se_demo_002", contactId: "c_demo_023", to: "henrik@arcfield.example", subject: "Arcfield — opener", body: "Hi Henrik,\n\nWe help VPs Sales like you ship 30% more pipeline.\n\n— You", scheduledFor: D(1), status: "scheduled", createdAt: D(-1), sentAt: "" },
];

export const SEED_SUPPRESSION: SuppressionEntry[] = [
  { id: "sp_demo_001", email: "bounced@example.invalid", reason: "bounce", source: "auto", createdAt: D(-15) },
  { id: "sp_demo_002", email: "optout@brand.example", reason: "unsubscribe", source: "auto", createdAt: D(-10) },
  { id: "sp_demo_003", email: "donotcontact@silentco.example", reason: "manual", source: "you@yourco.example", createdAt: D(-5) },
];

export const SEED_SNIPPETS: Snippet[] = [
  { id: "sn_demo_001", trigger: "/sig", name: "Default signature", body: "— You\nyourco.com\nhttps://cal.com/you/15min", createdAt: D(-30) },
  { id: "sn_demo_002", trigger: "/intro", name: "Intro line", body: "I'll keep this short — we help VPs of Sales ship 30% more pipeline with AI-personalized outreach.", createdAt: D(-21) },
  { id: "sn_demo_003", trigger: "/cal", name: "Calendar link", body: "Grab a 15-min slot here: https://cal.com/you/15min", createdAt: D(-14) },
  { id: "sn_demo_004", trigger: "/case", name: "Case study", body: "Recent customer (similar size to yours) cut SDR ramp time in half. Happy to share a redacted case study.", createdAt: D(-7) },
];

export const SEED_PIPELINES: Pipeline[] = [
  {
    id: "pl_default",
    name: "Standard",
    stages: JSON.stringify([
      "discovery",
      "evaluation",
      "proposal",
      "negotiation",
      "won",
      "lost",
    ]),
    isDefault: "yes",
    createdAt: D(-30),
  },
  {
    id: "pl_enterprise",
    name: "Enterprise",
    stages: JSON.stringify([
      "discovery",
      "evaluation",
      "security-review",
      "proposal",
      "negotiation",
      "won",
      "lost",
    ]),
    isDefault: "no",
    createdAt: D(-30),
  },
];

export const SEED_DEALS: Deal[] = [
  {
    id: "d_demo_001",
    name: "Northwind — Q3 expansion",
    pipelineId: "pl_default",
    stage: "negotiation",
    probability: "0.7",
    value: 36000,
    expectedCloseDate: D(14).slice(0, 10),
    owner: "you@yourco.example",
    splits: JSON.stringify([
      { owner: "you@yourco.example", pct: 70 },
      { owner: "alex@yourco.example", pct: 30 },
    ]),
    contactIds: "c_demo_001,c_demo_007,c_demo_012",
    companyId: "co_demo_001",
    contractStatus: "drafting",
    lostReason: "",
    winReason: "",
    stageEnteredAt: D(-2),
    notes: "Multi-stakeholder; needs security review.",
    createdAt: D(-21),
    updatedAt: D(-2),
    closedAt: "",
  },
  {
    id: "d_demo_002",
    name: "Brightleaf — annual",
    pipelineId: "pl_default",
    stage: "proposal",
    probability: "0.55",
    value: 24000,
    expectedCloseDate: D(10).slice(0, 10),
    owner: "you@yourco.example",
    splits: JSON.stringify([{ owner: "you@yourco.example", pct: 100 }]),
    contactIds: "c_demo_002,c_demo_015",
    companyId: "co_demo_002",
    contractStatus: "",
    lostReason: "",
    winReason: "",
    stageEnteredAt: D(-1),
    notes: "Trial-to-paid pending.",
    createdAt: D(-14),
    updatedAt: D(-1),
    closedAt: "",
  },
  {
    id: "d_demo_003",
    name: "Summit Financial — multi-year",
    pipelineId: "pl_enterprise",
    stage: "evaluation",
    probability: "0.3",
    value: 60000,
    expectedCloseDate: D(45).slice(0, 10),
    owner: "alex@yourco.example",
    splits: JSON.stringify([{ owner: "alex@yourco.example", pct: 100 }]),
    contactIds: "c_demo_009",
    companyId: "co_demo_003",
    contractStatus: "",
    lostReason: "",
    winReason: "",
    stageEnteredAt: D(-4),
    notes: "Series C fintech; security review next.",
    createdAt: D(-30),
    updatedAt: D(-4),
    closedAt: "",
  },
  {
    id: "d_demo_004",
    name: "Apex Partners — pilot",
    pipelineId: "pl_default",
    stage: "won",
    probability: "1",
    value: 18000,
    expectedCloseDate: D(-3).slice(0, 10),
    owner: "you@yourco.example",
    splits: JSON.stringify([{ owner: "you@yourco.example", pct: 100 }]),
    contactIds: "c_demo_004",
    companyId: "",
    contractStatus: "signed",
    lostReason: "",
    winReason: "Warm referral; small pilot scope.",
    stageEnteredAt: D(-3),
    notes: "Closed; kickoff scheduled.",
    createdAt: D(-7),
    updatedAt: D(-3),
    closedAt: D(-3),
  },
  {
    id: "d_demo_005",
    name: "Harborline — re-engagement",
    pipelineId: "pl_default",
    stage: "lost",
    probability: "0",
    value: 0,
    expectedCloseDate: D(-10).slice(0, 10),
    owner: "you@yourco.example",
    splits: JSON.stringify([{ owner: "you@yourco.example", pct: 100 }]),
    contactIds: "c_demo_010",
    companyId: "",
    contractStatus: "",
    lostReason: "Chose competitor (existing relationship).",
    winReason: "",
    stageEnteredAt: D(-10),
    notes: "Re-engage in 6 months.",
    createdAt: D(-25),
    updatedAt: D(-10),
    closedAt: D(-10),
  },
  {
    id: "d_demo_006",
    name: "Vellum Pay — fast-track",
    pipelineId: "pl_default",
    stage: "discovery",
    probability: "0.15",
    value: 48000,
    expectedCloseDate: D(30).slice(0, 10),
    owner: "alex@yourco.example",
    splits: JSON.stringify([{ owner: "alex@yourco.example", pct: 100 }]),
    contactIds: "c_demo_022",
    companyId: "",
    contractStatus: "",
    lostReason: "",
    winReason: "",
    stageEnteredAt: D(-1),
    notes: "Inbound from form; high intent.",
    createdAt: D(-1),
    updatedAt: D(-1),
    closedAt: "",
  },
  {
    id: "d_demo_007",
    name: "Verdant Grid — annual",
    pipelineId: "pl_default",
    stage: "won",
    probability: "1",
    value: 42000,
    expectedCloseDate: D(-1).slice(0, 10),
    owner: "you@yourco.example",
    splits: JSON.stringify([{ owner: "you@yourco.example", pct: 100 }]),
    contactIds: "c_demo_030",
    companyId: "co_demo_006",
    contractStatus: "signed",
    lostReason: "",
    winReason: "Strong climate-tech fit; champion in seat.",
    stageEnteredAt: D(-1),
    notes: "",
    createdAt: D(-22),
    updatedAt: D(-1),
    closedAt: D(-1),
  },
  {
    id: "d_demo_008",
    name: "Helix Medical — enterprise",
    pipelineId: "pl_enterprise",
    stage: "evaluation",
    probability: "0.2",
    value: 30000,
    expectedCloseDate: D(60).slice(0, 10),
    owner: "sam@yourco.example",
    splits: JSON.stringify([{ owner: "sam@yourco.example", pct: 100 }]),
    contactIds: "c_demo_005,c_demo_024",
    companyId: "co_demo_004",
    contractStatus: "",
    lostReason: "",
    winReason: "",
    stageEnteredAt: D(-15),
    notes: "Long sales cycle; security review pending.",
    createdAt: D(-20),
    updatedAt: D(-2),
    closedAt: "",
  },
];

export const SEED_MEMBERS: Member[] = [
  { id: "m_demo_001", email: "you@yourco.example", name: "You (Demo)", role: "admin", signature: "— You\nyourco.com", timezone: "America/Los_Angeles", active: "yes", createdAt: D(-30) },
  { id: "m_demo_002", email: "alex@yourco.example", name: "Alex Rivera", role: "rep", signature: "— Alex\nSenior AE", timezone: "America/New_York", active: "yes", createdAt: D(-25) },
  { id: "m_demo_003", email: "sam@yourco.example", name: "Sam Patel", role: "rep", signature: "— Sam", timezone: "Europe/London", active: "yes", createdAt: D(-18) },
  { id: "m_demo_004", email: "jordan@yourco.example", name: "Jordan Lee", role: "viewer", signature: "", timezone: "America/Chicago", active: "yes", createdAt: D(-7) },
];

export const SEED_AUDIT: AuditEntry[] = [
  { id: "au_demo_001", actor: "you@yourco.example", action: "create", entity: "lead", entityId: "l_demo_030", diff: '{"stage":["—","won"]}', createdAt: D(-1) },
  { id: "au_demo_002", actor: "alex@yourco.example", action: "update", entity: "contact", entityId: "c_demo_002", diff: '{"tags":["ICP","ICP, replied"]}', createdAt: D(-1) },
  { id: "au_demo_003", actor: "sam@yourco.example", action: "create", entity: "task", entityId: "t_demo_005", diff: '{"title":["—","Send Summit Financial proposal"]}', createdAt: D(-2) },
];

export const SEED_VIEWS: SavedView[] = [
  {
    id: "v_demo_001",
    name: "Hot ICPs",
    filter: '{"tag":"ICP","minScore":80}',
    createdAt: D(-7),
  },
  {
    id: "v_demo_002",
    name: "Untouched leads",
    filter: '{"stage":"new"}',
    createdAt: D(-7),
  },
  { id: "v_demo_003", name: "Replied this week", filter: '{"tag":"replied"}', createdAt: D(-5) },
  { id: "v_demo_004", name: "Founders ICP", filter: '{"tag":"founder"}', createdAt: D(-3) },
  { id: "v_demo_005", name: "Healthcare pipeline", filter: '{"tag":"healthcare","minScore":60}', createdAt: D(-2) },
];
