// Diagram → DOCX, PPTX, HTML, Markdown, DXF exporters.
// These bridge into the existing /lib/docs/ and /lib/slides/ engines
// so we don't reinvent the OOXML packagers — except DXF which is
// plain ASCII.

import { exportSvg } from './svg-export.js';
import { exportPng } from './png-export.js';

const PX_PER_IN = 96;

// ---------- HTML export ----------
// Self-contained single-file HTML with inline SVG per page,
// clickable hyperlinks, and an expandable comments section.

export function exportHtml(diagram) {
  const pages = diagram.pages || [];
  const title = escapeHtml(diagram.title || 'Diagram');
  const pagesHtml = pages.map((page, i) => {
    const svg = exportSvg(diagram, { pageIndex: i });
    // Collect hyperlinks + comments for the sidebar.
    const links = [];
    const comments = [];
    for (const s of page.shapes) {
      (s.hyperlinks || []).forEach((h) => links.push({ shape: s.text || s.stencil, ...h }));
      (s.comments || []).forEach((c) => comments.push({ shape: s.text || s.stencil, ...c }));
    }
    return `<section class="page">
  <h2>${escapeHtml(page.name)}</h2>
  <div class="canvas">${svg}</div>
  ${links.length ? `<h3>Hyperlinks</h3><ul>${links.map((l) =>
    `<li><b>${escapeHtml(l.shape)}</b>: <a href="${escapeHtml(l.target)}">${escapeHtml(l.label || l.target)}</a></li>`).join('')}</ul>` : ''}
  ${comments.length ? `<h3>Comments</h3><ul>${comments.map((c) =>
    `<li><b>${escapeHtml(c.shape)}</b> · ${escapeHtml(c.author || '')}: ${escapeHtml(c.text)}</li>`).join('')}</ul>` : ''}
</section>`;
  }).join('\n');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${title}</title>
<style>
body { font-family: 'Segoe UI', sans-serif; max-width: 1100px; margin: 24px auto; padding: 0 16px; color: #1f2937; }
h1 { font-size: 22px; border-bottom: 2px solid #1a8e9a; padding-bottom: 4px; }
h2 { font-size: 16px; color: #1a8e9a; margin-top: 32px; }
h3 { font-size: 13px; color: #475569; margin-top: 16px; }
.page { page-break-after: always; }
.canvas { border: 1px solid #e5e7eb; padding: 8px; background: #fff; overflow-x: auto; }
.canvas svg { max-width: 100%; height: auto; }
ul { padding-left: 18px; font-size: 13px; }
li { margin: 4px 0; }
footer { margin-top: 48px; padding-top: 12px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #94a3b8; }
</style>
</head>
<body>
<h1>${title}</h1>
${pagesHtml}
<footer>Generated by RodmanVision</footer>
</body>
</html>`;
  return new Blob([html], { type: 'text/html' });
}

// ---------- Markdown export ----------
// Each page becomes an H2 plus an inline base64 PNG plus a table of
// shape data fields (when any exist).

export async function exportMarkdown(diagram) {
  const pages = diagram.pages || [];
  const parts = [`# ${diagram.title || 'Diagram'}`, ''];
  for (let i = 0; i < pages.length; i++) {
    const page = pages[i];
    parts.push(`## ${page.name || `Page ${i + 1}`}`);
    parts.push('');
    const blob = await exportPng(diagram, { pageIndex: i, scale: 2 });
    const dataUrl = await blobToDataUrl(blob);
    parts.push(`![${escapeMd(page.name)}](${dataUrl})`);
    parts.push('');
    // Shape data table
    const fields = new Set();
    for (const s of page.shapes) {
      if (s.data) Object.keys(s.data).forEach((f) => fields.add(f));
    }
    if (fields.size) {
      const cols = ['Shape', 'Stencil', ...fields];
      parts.push('| ' + cols.join(' | ') + ' |');
      parts.push('|' + cols.map(() => '---').join('|') + '|');
      for (const s of page.shapes) {
        const row = [escapeMd(s.text || ''), escapeMd(s.stencil)];
        for (const f of fields) {
          const v = s.data && s.data[f];
          row.push(escapeMd(v ? (v.value != null ? v.value : v) : ''));
        }
        parts.push('| ' + row.join(' | ') + ' |');
      }
      parts.push('');
    }
  }
  return new Blob([parts.join('\n')], { type: 'text/markdown' });
}

// ---------- DXF export (basic LINE/POLYLINE wireframe) ----------
// Produces ASCII DXF readable by AutoCAD / QCAD / LibreOffice Draw.
// We emit each shape's bounding rectangle as a POLYLINE and each
// connector segment as a LINE. No fill, no text, no real geometry —
// this is a wireframe export, not a full Visio→AutoCAD bridge.

export function exportDxf(diagram) {
  const lines = [];
  function pair(code, value) { lines.push(String(code)); lines.push(String(value)); }

  pair(0, 'SECTION');
  pair(2, 'HEADER');
  pair(0, 'ENDSEC');
  pair(0, 'SECTION');
  pair(2, 'ENTITIES');

  for (const page of diagram.pages || []) {
    const ph = page.h;
    for (const s of page.shapes) {
      // Bounding rectangle as a closed polyline. DXF Y axis grows
      // upward, our Y axis grows downward — flip with page height.
      pair(0, 'LWPOLYLINE');
      pair(8, '0');             // layer
      pair(90, 4);              // vertex count
      pair(70, 1);              // closed
      // 4 vertices
      [[s.x, s.y], [s.x + s.w, s.y], [s.x + s.w, s.y + s.h], [s.x, s.y + s.h]].forEach(([x, y]) => {
        pair(10, x.toFixed(3));
        pair(20, (ph - y).toFixed(3));
      });
      if (s.text) {
        pair(0, 'TEXT');
        pair(8, '0');
        pair(10, (s.x + s.w / 2).toFixed(3));
        pair(20, (ph - s.y - s.h / 2).toFixed(3));
        pair(40, '8');           // height
        pair(1, String(s.text).replace(/\n/g, ' '));
      }
    }
    for (const c of page.connectors) {
      const from = page.shapes.find((sh) => sh.id === c.fromShapeId);
      const to = page.shapes.find((sh) => sh.id === c.toShapeId);
      if (!from || !to) continue;
      const a = portPoint(from, c.fromPort);
      const b = portPoint(to, c.toPort);
      pair(0, 'LINE');
      pair(8, '0');
      pair(10, a.x.toFixed(3));
      pair(20, (ph - a.y).toFixed(3));
      pair(11, b.x.toFixed(3));
      pair(21, (ph - b.y).toFixed(3));
    }
  }

  pair(0, 'ENDSEC');
  pair(0, 'EOF');

  return new Blob([lines.join('\n')], { type: 'application/dxf' });
}

// ---------- DOCX / PPTX export ----------
// Bridge into lib/docs and lib/slides. Each page → one image.

export async function exportDocx(diagram, docsLib) {
  if (!docsLib || !docsLib.saveDocx) throw new Error('Word engine not loaded');
  const pages = diagram.pages || [];
  let html = `<h1>${escapeHtml(diagram.title || 'Diagram')}</h1>`;
  for (let i = 0; i < pages.length; i++) {
    const page = pages[i];
    html += `<h2>${escapeHtml(page.name || `Page ${i + 1}`)}</h2>`;
    const blob = await exportPng(diagram, { pageIndex: i, scale: 2 });
    const dataUrl = await blobToDataUrl(blob);
    html += `<p><img src="${dataUrl}" /></p>`;
  }
  return docsLib.saveDocx(html, { title: diagram.title || 'Diagram' });
}

// PPTX bridge: convert each diagram page into a deck slide with a
// single full-bleed image element. Reuses the html-bridge htmlToDeck
// pattern via slidesLib.savePptx + a tiny deck literal.
export async function exportPptx(diagram, slidesLib) {
  if (!slidesLib || !slidesLib.savePptx) throw new Error('Slides engine not loaded');
  const pages = diagram.pages || [];
  const slides = [];
  for (let i = 0; i < pages.length; i++) {
    const blob = await exportPng(diagram, { pageIndex: i, scale: 2 });
    const dataUrl = await blobToDataUrl(blob);
    slides.push({
      id: `s-${i}`,
      layout: 'blank',
      background: { kind: 'theme' },
      transition: { kind: 'none', durationMs: 400 },
      notes: '',
      elements: [
        { id: `e-${i}`, kind: 'image', x: 0, y: 0, w: 1280, h: 720, src: dataUrl },
      ],
    });
  }
  const deck = {
    schema: 1,
    title: diagram.title || 'Diagram',
    theme: 'office',
    size: { w: 1280, h: 720 },
    slides,
  };
  return slidesLib.savePptx(deck);
}

// ---------- Helpers ----------

function portPoint(shape, port) {
  switch (port) {
    case 'top':    return { x: shape.x + shape.w / 2, y: shape.y };
    case 'right':  return { x: shape.x + shape.w,     y: shape.y + shape.h / 2 };
    case 'bottom': return { x: shape.x + shape.w / 2, y: shape.y + shape.h };
    case 'left':   return { x: shape.x,               y: shape.y + shape.h / 2 };
    default:       return { x: shape.x + shape.w / 2, y: shape.y + shape.h / 2 };
  }
}

function blobToDataUrl(blob) {
  return new Promise((resolve, reject) => {
    const r = new FileReader();
    r.onload = () => resolve(r.result);
    r.onerror = () => reject(r.error);
    r.readAsDataURL(blob);
  });
}

function escapeHtml(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function escapeMd(s) {
  return String(s == null ? '' : s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
}
